### ISSUE TITLE
버튼(스위치) 연결

### ISSUE THREAD

**Issue by punkyoon** [eswww/pi-snap-cam-driver#4]
## Tip

버튼(스위치)는 GPIO pin 한 개와, GND만 연결해주면 됩니다.

- [x] 버튼 동작 확인 코드 작성

**Comment by SoYoung210** [comment]
https://github.com/derekmolloy/exploringBB/blob/master/extras/kernel/button/button.c

참고용 주소. 

- mknod.sh 

- btn_app : 버튼 확인용 앱코드 ` scanf("%c" )` 형태로 그냥 기다리는 중. 

- btn.c  = ko 만드는 코드

**Comment by punkyoon** [comment]
## 풀업 저항 연결

![image](https://user-images.githubusercontent.com/11442383/41194655-10d8c62c-6c5a-11e8-87ac-856e00a0488d.png)

## 참고자료

https://kocoafab.cc/tutorial/view/526

풀업 저항 형식으로 연결하지 않으면, 버튼이 폭주한다.....^^;;
